services:
  category.api:
    image: rentalcar.categories.api
    restart: always
    depends_on:
      - category.db
    build:
      context: .
      dockerfile: RentalCar.Categories.Api/Dockerfile
    container_name: category.api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "802:8080"
      - "803:8081"
    volumes:
      - category_log:/logs

  category.db:
    image: mysql:8.0.40
    restart: always
    container_name: category.mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin2k24@
    ports:
      - "3307:3306"
    volumes:
      - category_data:/var/lib/mysql
      
volumes:
  category_log:
  category_data:
