services:
  rentalcar.categories.api:
    image: rentalcar.categories.api    
    depends_on:
      - category.db
    build:
      context: .
      dockerfile: RentalCar.Categories.Api/Dockerfile
    container_name: category.api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "800:8080"
      - "801:8081"
    volumes:
      - category.log:/var/log

  category.db:
    image: mysql:8.0.40
    restart: always
    container_name: category.mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin2k24@
    ports:
      - "3307:3306"
    volumes:
      - categoryData:/var/lib/mysql
  
volumes:
  category.log:
  categoryData: